'use client';

import * as React from 'react';
import Link from 'next/link';
import { ShieldCheck, Scale, Lock, Eye, CheckCircle2, FileText, ArrowLeft, Info, Cpu, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { SiteHeader } from '@/components/nyaya/site-header';
import { SiteFooter } from '@/components/nyaya/site-footer';

export default function TrustCenterPage() {
  const principles = [
    {
      icon: Cpu,
      title: 'AI Boundaries & Transparency',
      desc: 'Nyaya AI provides informational, analytical, and organizational assistance. It strictly never acts as a licensed advocate or replaces court adjudication.',
    },
    {
      icon: Lock,
      title: 'Confidentiality & Zero Public Training',
      desc: 'Your private case description, uploaded rent agreements, and receipts are encrypted. No user documents or personal legal facts are ever sent to public model training.',
    },
    {
      icon: Scale,
      title: 'Verifiable Statutory Sources',
      desc: 'Every legal synthesis is backed by exact statutory acts (e.g., Transfer of Property Act, Contract Act, Consumer Protection Act) and supreme court precedents.',
    },
    {
      icon: Users,
      title: 'Human-in-the-Loop Governance',
      desc: 'Case Package Dossiers and Legal Notices generated by Nyaya explicitly require advocate review before formal court reliance or filing.',
    },
    {
      icon: Eye,
      title: 'Anonymized Pattern Discovery',
      desc: 'Systemic issue detection aggregates anonymized patterns across multiple complaints without exposing any citizen PII or individual identity.',
    },
    {
      icon: CheckCircle2,
      title: 'No Win Probability Claims',
      desc: 'Nyaya AI strictly evaluates case readiness categorically (Case Info, Evidence, Legal Review, Action Readiness). We never display misleading percentage win predictions.',
    },
  ];

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <SiteHeader />

      <main className="flex-1 pt-24 pb-16">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 space-y-8">
          {/* Header */}
          <div className="text-center space-y-3">
            <Badge variant="outline" className="border-amber-500/30 bg-amber-500/10 text-amber-800 dark:text-amber-400 font-bold text-xs">
              <ShieldCheck className="h-3.5 w-3.5 mr-1 text-amber-600 dark:text-amber-400" />
              Trust &amp; Safety Center
            </Badge>
            <h1 className="font-display text-3xl sm:text-4xl font-bold tracking-tight text-foreground">
              How Nyaya AI Works
            </h1>
            <p className="text-sm text-muted-foreground max-w-2xl mx-auto leading-relaxed">
              Understand our legal safety standards, data handling principles, AI limitations, and commitment to transparency.
            </p>
          </div>

          {/* Core Principles Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {principles.map((p, idx) => (
              <div key={idx} className="legal-card p-5 space-y-2 flex flex-col justify-between">
                <div className="space-y-2">
                  <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-amber-500/10 text-amber-700 dark:text-amber-400">
                    <p.icon className="h-5 w-5" />
                  </div>
                  <h3 className="font-display text-sm font-bold text-foreground">{p.title}</h3>
                  <p className="text-xs text-muted-foreground leading-relaxed">{p.desc}</p>
                </div>
              </div>
            ))}
          </div>

          {/* Legal Safety Banner */}
          <div className="rounded-2xl border border-amber-500/30 bg-amber-500/10 p-6 space-y-3 text-xs">
            <div className="flex items-center gap-2 text-amber-900 dark:text-amber-300 font-bold text-sm">
              <Info className="h-4 w-4 text-amber-600 dark:text-amber-400 shrink-0" />
              <span>Standard Legal Disclaimer</span>
            </div>
            <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
              Nyaya AI is designed to help citizens understand their legal rights, organize evidence, explore resolution pathways, and prepare structured case packages. Information on this platform does not constitute formal legal advice or create an attorney-client relationship. Citizens should consult a qualified advocate or their local District Legal Services Authority (DLSA) for professional representation.
            </p>
          </div>

          <div className="flex items-center justify-between pt-4 border-t border-border/60">
            <Button asChild variant="ghost" size="sm" className="text-xs">
              <Link href="/">
                <ArrowLeft className="h-3.5 w-3.5 mr-1" />
                Back to Home
              </Link>
            </Button>
            <Button asChild size="sm" className="bg-slate-900 text-slate-50 hover:bg-slate-800 dark:bg-amber-500 dark:text-slate-950 font-semibold text-xs rounded-xl">
              <Link href="/chat">Start Legal Journey</Link>
            </Button>
          </div>
        </div>
      </main>

      <SiteFooter />
    </div>
  );
}
